### ISSUE TITLE
Resources css

### ISSUE THREAD

**Issue by Handyfon** [ardittristan/5eSheet-resourcesPlus#1]
Hey, consider adding this css to your module:

```
.dnd5e.sheet.actor ul.attributes li.attribute {
    display: table;
    width: 100px;
}
.attributes .attribute:last-child {
    width: 10px;
}
```
it fixes the display of multiple resources:
![image](https://user-images.githubusercontent.com/28778881/83619832-b346fd80-a58c-11ea-8dd5-b3bf5515667a.png)

**Comment by ardittristan** [comment]
Implemented with 7f4226bcb5980e271c224c8013036f6a01eaf530
