### ISSUE TITLE
[Bug] "Use new settings location?" is checked, but the game is using the local limit.

### ISSUE THREAD

**Issue by SearingRains** [ardittristan/5eSheet-resourcesPlus#17]
Basically the title, hadn't encountered this before, but not 100% sure on when it started. Let me know if additional info is needed! Thanks for all your work on this! <3

**Comment by ardittristan** [comment]
what do you mean with local limit? that setting refers to the resource limit setting appearing in sheet settings instead of being inside an extra resource.

**Comment by SearingRains** [comment]
So when I loaded Foundry today and was checking my player's sheets, they all only had 1 resource, instead of the resource number inside of their "sheet" count. I checked, and my local resource limit was set to 1. I changed that to 9, and then everyone's sheet showed 9, instead of their local limit. 

Use new settings location is enabled. I hadn't changed any settings recently at all, or added any new modules. So I'm not sure if I am doing something wrong or misunderstanding something, but hopefully that clarifies what is going on? I think I expect it to follow the individual sheets' resources, and not whatever the local limit is. Again, I am really sorry to bother you, especially if I am being dumb. But I appreciate your help and response!

**Comment by ardittristan** [comment]
ah, local resource limit is global for yourself, but only yourself. global resource limit is for everyone. so if you change your local limit you'll see less, but everyone else will still see more. If you want to change the resource count per-sheet you can do that in the options in the sheet header.

**Comment by SearingRains** [comment]
Yup! Last question, and (and please feel free to close this now; again, really appreciate the response). I do in fact have the sheets set at different counts, which was working 100% as intended before. But I had just noticed today it was only showing 1 on each sheet for me, which happened to be the local limit. Previously, all sheets were showing what the sheet count was set to; now it's only showing the local limit on all of my sheets (as GM). And I hadn't changed any settings or anything. It isn't a big deal at all for me so definitely feel free to close this, but just seems a bit different to me, when I think it was working perfectly before haha.

**Comment by SearingRains** [comment]
I must be really stupid. Somehow my local limit must have changed. I set it to -1, and all sheets are showing correctly. I have no idea how it got set to 1. I am so sorry to have wasted your time. Thank you very much!
