### ISSUE TITLE
Resource Count Not Changing on Foundry v10

### ISSUE THREAD

**Issue by bearsy1** [ardittristan/5eSheet-resourcesPlus#25]
Foundry version: 10.284
5e-Sheet Resource Plus version: 1.7.0
Game system: DnD5e 2.0.2
Default sheet: Tidy5e (but also tested with default sheet)

I might be missing something obvious, but the amount of resources do not seem to update when changed on a character's sheet. 

With the option of "show everything" not ticked and local limit set to 9, the sheet initially shows 9 resource slots as intended on both the default and Tidy5e sheet, but when I go to edit the "Resource Count" on a given sheet -- to say 3 -- the resource slots on the sheet do not change/update.

**Comment by ardittristan** [comment]
local limit has priority over actor limits, maybe I should've worded the setting better, sorry

**Comment by Wraithlord2015** [comment]
There's apparently a change that was made to how the 5e core saves data. This causes the resource changes to not be over ridden on the sheets. So no matter what option you adjust, it never updates it properly when adjusted. See bugs # 26 & 27 that were opened.
