### ISSUE TITLE
Resources are always on Max

### ISSUE THREAD

**Issue by Kharmans** [ardittristan/5eSheet-resourcesPlus#26]
With the update 2.1.1 of DnD5e System, the module always show the maximum Resources on the sheet. Even if you change that number, the max resource will always show.

![image](https://user-images.githubusercontent.com/112586547/211920866-0f1060b2-062f-45c5-8035-4fc67f871ef0.png)

![image](https://user-images.githubusercontent.com/112586547/211921016-6d8e0c11-4131-4d64-91fc-a41036f587a3.png)

![image](https://user-images.githubusercontent.com/112586547/211921062-4f58f043-ea34-4ccb-8867-d08aff67d730.png)

**Comment by SabreRunner** [comment]
If I may add, I can not set an individual resource number per sheet.

**Comment by Kharmans** [comment]
> If I may add, I can not set an individual resource number per sheet.

Yes!

**Comment by Wraithlord2015** [comment]
Ok got a response. Just waiting on fixes. :)
