### ISSUE TITLE
[BUG] Resource values not saving

### ISSUE THREAD

**Issue by Orionox** [ardittristan/5eSheet-resourcesPlus#27]
**Describe the bug**
Closing a character sheet resets the values entered into the extended resource values since the most recent 5e update. 

**To Reproduce**
Open character sheet, fill out values for resource, close character sheet, and resource values for resource 4+ will be empty.

**Setup:**
 - Foundry Version: [10.291]
 - System Version: [DND5e 2.1.2]

**Comment by krbz999** [comment]
Note for the dev:
The additional resources added by this module should be saved in the actor flags under the module scope, rather than attempting to inject new values into the System data, which is no longer possible in dnd5e as of v2.1.0 since it now has a SystemDataModel.

**Comment by Wraithlord2015** [comment]
Is this an issue with the module or the 5e core update? Just want to make sure it's reported in the correct place to fix it if possible.

**Comment by Orionox** [comment]
This is only for resources added by this module.

**Comment by tprussak** [comment]
> Is this an issue with the module or the 5e core update? Just want to make sure it's reported in the correct place to fix it if possible.

It is an issue with the module, but it is caused by the 5e core updating the way it stores data. The module needs to be updated to support the new data structures in the 5e core.

**Comment by Wraithlord2015** [comment]
> > Is this an issue with the module or the 5e core update? Just want to make sure it's reported in the correct place to fix it if possible.
> 
> It is an issue with the module, but it is caused by the 5e core updating the way it stores data. The module needs to be updated to support the new data structures in the 5e core.

Tks for a quick reply! I rely on this heavily - so hope it's fixed quickly.

**Comment by ardittristan** [comment]
I'm looking at it!
