### ISSUE TITLE
[Incompatability] with Token-Mold

### ISSUE THREAD

**Issue by NelanaPrime** [ardittristan/5eSheet-resourcesPlus#28]
Found a Compatibility issue with [Token-Mold](https://github.com/Moerill/token-mold). With both modules active (and libwrapper as a dependency) and no others, Token Mold throws an error and fails to function.

The creator of token mold requests Compatibility issues be brought up to the other module creator, so I'm putting this here, as well as there.

If they can't be made to work together that's fine, Just wanted to bring it to your attention in case it can be fixed, as I'd like to be able to use both modules together.

Error on Startup: 
https://i.imgur.com/WLpTqcj.png
https://i.imgur.com/sCztO2h.png

Error on Token Placement: https://i.imgur.com/mJcQyYY.png

1. Load up both Modules together, and that's it.

 - OS: Windows 10
 - Browser: Foundry Standalone
 - FVTT Version 10.291
 - Module version
 - Token-Mold: 2.15.4
 - 5eSheet-resourcesPlus : 1.8.0

**Comment by ardittristan** [comment]
I think this is correlated with issue #29 
Does it still happen after v1.8.1?

**Comment by NelanaPrime** [comment]
Indeed, After updating just now and testing, I'm no longer receiving these errors.
Thanks for getting it taken care of!
