### ISSUE TITLE
[Error] Error on Actor Create

### ISSUE THREAD

**Issue by mrgreenhippo** [ardittristan/5eSheet-resourcesPlus#29]
I can give additional information if needed/wanted, but in the attached screenshot you can see that I only have 5e-sheet Resources Plus and LibWrapper enabled. When I go to 'Create Actor' this is the error that appears. Resources seem to work as intended on already created actors.
This is 5e version 2.1.4 and foundry version 10 - build 291.
I have made slight modifications to the 5e version to increase the number of death failures allowed, but I don't believe those changes should effect this.
![image](https://user-images.githubusercontent.com/35243015/219282167-4ea91d72-7683-4e72-8b82-f7d31a62b990.png)

**Comment by Red5Phil** [comment]
I can confirm I am having the exact same experience. The issue can be replicated by activating both this module as well as libwrapper.

**Comment by 9ryex5** [comment]
This is still happening, if the "Global resource limit" is less than 20, there's an error for each value below 20.

![image](https://user-images.githubusercontent.com/43207603/224128276-f4555235-2bb8-464c-9c1b-99041ccd5ae4.png)
