### ISSUE TITLE
Can not create a new PC

### ISSUE THREAD

**Issue by Jakimcio** [ardittristan/5eSheet-resourcesPlus#31]
When trying to create a new PC it fails with the following log:

![image](https://user-images.githubusercontent.com/130793238/235093148-6cdfe480-fa2a-43bb-977b-e12918b52829.png)

I used Find the culprit to narrow it down to this module :)

**Comment by Jakimcio** [comment]
It works if I turn up the resource limit

**Comment by ardittristan** [comment]
Sorry for the late reply, will be fixed in the next release
