### ISSUE TITLE
[V11] Key for resources doesn't appear on token properties

### ISSUE THREAD

**Issue by megahead11** [ardittristan/5eSheet-resourcesPlus#32]
While the resources appear to be visible in v11 and can be edited (used as normal), they cannot be pulled up in the token's resource bar configuration. You cannot select "resources.fourth.max" or above on the dropdown list. 

![image](https://github.com/ardittristan/5eSheet-resourcesPlus/assets/21242682/055b83fe-2375-4e96-9560-42518043ef69)

**Comment by Bryn1701** [comment]
Was looking into updating to V11 but this is a must for my party, they have so many resources they want to keep track of. 3 just doesn't cut it for me.

**Comment by megahead11** [comment]
As of DnD 2.2.2, it appears  the resources are now further nonfunctional -- they appear on the sheet, but editing them doesn't do anything, as they will revert to the previous value upon re-opening -- alongside a number of other oddities by being absent in module interactions and 5esheet references.

**Comment by DJ4ddi** [comment]
Newer versions no longer traverse the template to find attributes and instead use the `CONFIG.Actor.trackableAttributes` global. The structure looks like this:
```js
{
  character: {
    bar: [ "path.to.res1", "path.to.res2" ],
    value: [ "path.to.attr1", "path.to.attr2" ],
  },
  npc: { bar: [], value: [] },
  vehicle: { bar: [], value: [] },
  group: { bar: [], value: [] },
}
```

The new resources must be added to this in order to be globally accessible as a resource.

**Comment by ardittristan** [comment]
I'll take a look at it this weekend!
