### ISSUE TITLE
Latest update throwing new error

### ISSUE THREAD

**Issue by SecretSquirrel77** [ardittristan/5eSheet-resourcesPlus#37]
Hello! I love your mod and it's super useful! 
With the latest update to V1.9, I see a new error in the console. This doesn't appear to stop me from using an extra (fourth) resource on Player Character sheets however. I am using the latest DnD5e and the latest version of Foundry. 
![image](https://github.com/ardittristan/5eSheet-resourcesPlus/assets/77705375/30940a56-0b90-4db8-8bce-d7158334cf55)
![image](https://github.com/ardittristan/5eSheet-resourcesPlus/assets/77705375/40e1369d-f2ca-4819-9c72-adcc7dbcea46)

**Comment by kgar** [comment]
I am experiencing the error as well. 
The error occurs before the compatibility code for Tidy 5e sheets, so Tidy sheets are unable to render additional resources correctly.

**Comment by ardittristan** [comment]
should be fixed
