### ISSUE TITLE
New Sheet 5e Compatibility

### ISSUE THREAD

**Issue by Liviu50** [ardittristan/5eSheet-resourcesPlus#38]
Is there any intention of updating the module for the new 5e sheet that dnd5e systems has made?
I noticed that if i add res BEFORE, it actually saves the resource as a favorite but cannot add more or do anything really besides modifying the values or deleting...which i guess in its behavior its luckily working but prolly by hopes and prayers :D.

Any intention to adapt the module for the new char sheet? cause i use spell points and this module is quite needed :)
Thanks and keep up the good work!

**Comment by krbz999** [comment]
The dnd5e system is intentionally deprecating all resources in favor of using items/features with limited uses.

**Comment by ardittristan** [comment]
has been added, lets hope they don't break it more in the future

**Comment by Liviu50** [comment]
lets hope so, thanks a bunch :) really useful mod!
