### ISSUE TITLE
What are resources?

### ISSUE THREAD

**Issue by CptTwinkie** [ardittristan/5eSheet-resourcesPlus#4]
I've played D&D for 20 years and I've never heard of "resources". I thought maybe I was missing something that was foundry-specific but after checking the 5E sheet, I honestly can't figure out what this module is for. I asked a couple of my friends and they didn't come up with anything either. Now we're all chatting about it and super curious. What are these mysterious resources?

**Comment by ardittristan** [comment]
On the attribute tab of your character sheets there's resource boxes, these can be used to track usage of things that only have limited amount of uses (eg druid wild shapes or ammo). By default foundry only has 3 resource boxes, but with this module you can have up to 20 resource boxes.
![image](https://user-images.githubusercontent.com/42787508/87607466-b0980600-c6fd-11ea-838b-6d38934d4aa5.png)

You can even have items automatically consume resources on use (bottom of img2)
![image](https://user-images.githubusercontent.com/42787508/87607601-01a7fa00-c6fe-11ea-9da1-8b11782630d0.png)

**Comment by CptTwinkie** [comment]
well, now I just feel silly. thanks for the thorough explanation.
