### ISSUE TITLE
Characters sheets do not open.

### ISSUE THREAD

**Issue by flynnkd** [ardittristan/5eSheet-resourcesPlus#43]
Using latest stable version of 12, character sheets will not open.

**Comment by twagorilla** [comment]
Same issue here

**Comment by jdbeel** [comment]
I just opened a PR which addresses this problem: #44

**Comment by jdbeel** [comment]
It's been a few days and I've not seen any comments on my PR regarding them getting merged in so I wanted to post this here for anyone who might be having the same problem as @flynnkd: You can use the release from my fork to get this module working on Foundry v12 while we wait for the PR to get merged. Hope this helps :) 

https://github.com/jdbeel/5eSheet-resourcesPlus/releases/tag/1.10.1

**Comment by jdbeel** [comment]
Seems like the PR was merged, so this issue is should be addressed whenever the new release is put out.
