### ISSUE TITLE
Two more compatible sheets

### ISSUE THREAD

**Issue by akrigline** [ardittristan/5eSheet-resourcesPlus#6]
[Compact DnDBeyond-like 5e Character Sheet](https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet) and [D&D 5e OGL Character Sheet](https://github.com/ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet) both work with resources plus.

The OGL Sheet ... while it does work and doesn't break anything it's far from pretty. The Compact DndBeyond sheet works well though.

**Comment by ardittristan** [comment]
Both seem to work fine with me, thanks! Only difference between OGL and DnDBeyond I notice is that one is horizontal with vertical scrollbar and the other is vertical with vertical scrollbar.
