### ISSUE TITLE
issue with 0.7.5?

### ISSUE THREAD

**Issue by Newber92** [ardittristan/5eSheet-resourcesPlus#8]
I have many resources setup to be connected to inventory or features (Detail page of each item, Resource Consumption, ressource.primary.value or whatever resource needed) and it was working splendidly before the 0.7.5 update. Now when I roll these linked features/items the resources in the main Character Sheet are not impacted. Is that something due to the new update?

**Comment by ardittristan** [comment]
hm, it seems to work fine for me, are any errors showing up in the console when you try it? (f12)
I don't have actors with linked attributes from before 0.7.5, if there is no errors, could you try changing the consumption value to something else and then back?

**Comment by Newber92** [comment]
EDIT: screenshots below.

**Comment by ardittristan** [comment]
The images dont work for me, could you maybe try posting them via github instead of email?

**Comment by Newber92** [comment]
I'm sorry see below:

Resources on "Attributes" tab of Character Sheet:
https://ibb.co/fYFwY1C

Details of the Feature linked to the first resource:
https://ibb.co/GVph9Q3

Mod settings:
https://ibb.co/mBHwDtk

The console when I roll that feature now:
https://ibb.co/VtXWVYh

Again, thank you.

**Comment by ardittristan** [comment]
I'm able to replicate it now, it has something to do with better rolls being enabled. Let me check if I can figure out what's happening.

**Comment by Newber92** [comment]
100% correct, just tried after deactivating Better Rolls and it worked perfectly.

**Comment by ardittristan** [comment]
![image](https://user-images.githubusercontent.com/42787508/97049647-5c15e980-157c-11eb-865c-3c5b26e491aa.png)
you'll have to enable resource under better roll settings, then it works for me

**Comment by Newber92** [comment]
I feel like a chump that's such an easy fix. It works! Thanks a lot for your help.

**Comment by ardittristan** [comment]
Np! happy DND'ing!
